name: Verilog Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Install Verible linter
      - name: Install Verible
        run: |
          wget https://github.com/chipsalliance/verible/releases/download/v0.0-3644-g9c1c8855/verible-v0.0-3644-g9c1c8855-linux-static-x86_64.tar.gz
          tar -xzf verible-v0.0-3644-g9c1c8855-linux-static-x86_64.tar.gz
          sudo mv verible-v0.0-3644-g9c1c8855/bin/* /usr/local/bin/
          verible-verilog-lint --version
      
      # Step 3: Run Verible linter on all Verilog files
      - name: Lint Verilog files
        run: |
          echo "Running Verible linter on all .v files..."
          find . -name "*.v" -type f | while read file; do
            echo "Linting: $file"
            verible-verilog-lint "$file" || true
          done
          
          echo "Linting complete!"
