name: Synthesis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  synthesize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Yosys
      run: sudo apt-get install -y yosys

    - name: Run synthesis
      run: |
        yosys -p "synth -top top_module" 1.Getting\ Started/step_one.v
        yosys -p "synth -top top_module" 1.Getting\ Started/zero.v
        yosys -p "synth -top ALU" Misc/32-bit-CPU/arithmetic_logic_unit.v
        yosys -p "synth -top ControlUnit" Misc/32-bit-CPU/control_unit.v
        yosys -p "synth -top CPU" Misc/32-bit-CPU/datapath.v
        yosys -p "synth -top RegisterFile" Misc/32-bit-CPU/register_file.v
        yosys -p "synth -top sha256_core" Misc/BruteForce/sha256.v
        yosys -p "synth -top elevator_1floor" Misc/Elevator/1-Floor\ Elevator.v
        yosys -p "synth -top elevator_2floor" Misc/Elevator/2-Floor\ Eleavtor.v
        yosys -p "synth -top elevator_1floor_lock" Misc/Elevator/elevator_1floor_lock.v
        yosys -p "synth -top elevator_2floor_lock" Misc/Elevator/elevator_2floor_lock.v
        yosys -p "synth -top elevator_3floor" Misc/Elevator/elevator_3floor.v
        yosys -p "synth -top elevator_3floor" Misc/Elevator/elevator_3floor_lock.v
        yosys -p "synth -top usb_interface" Misc/USB/usb_interface.v
        yosys -p "synth -top readonly_device" readonly_device.v
        yosys -p "synth -top rom_memory" rom_memory.v
        yosys -p "synth -top write_only_device" write_only_device.v
        yosys -p "synth -top implication_gate" Test/testbench.v
